### ISSUE TITLE
AWS EC2 서버 구축 및 배포

### ISSUE THREAD

**Issue by NaMooJoon** [ChatCode9/ChatCode-backend#11]
### 🤔 Describe

배포를 위한 API 서버를 구축하기 위해 AWS EC2 인스턴스를 생성하고 Spring API 서버를 배포합니다.

### ✅ Tasks

- [x] EC2 인스턴스 생성
  - [x] Elastic IP 등록
  - [x] 인바운딩 rules 등록
- [x] Web 서버 배포 (Spring Boot) 
  - [x] Git 설치
  - [x] JDK 설치
  - [x] Docker 설치
  - [x] Docker-compose
  - [x] 웹서버 배포

### 🙋🏻 More

우선 간단하게 Tasks를 작성했습니다! 혹시나 추가적으로 더 셋팅해야 할 것들이 있다면 댓글로 알려주세요 ~

**Comment by NaMooJoon** [comment]
- [x] AWS EC2 서버 구축하기
	- [x] 계정 새로 파기
	- [x] EC2 Instance 생성
		- [x] t2 (cpu 토큰 => 일정 ), t4!!!!
		- [x] **서울 지역에서 t3까지만 지원** 가능.
			- [x] T3는 좀 더 안정적인 서버로 T2 성능에 비해 네트워크 성능이 향상되고 동일 성능으로 비교시 T2보다 30% 저렴하다.
			- [x] **하지만 지금 free tier로 T2를 1년 동안 무료로 사용 가능** => 개발동안은 T2 써도 될 것 같다.
	- [x] .pem 키 발급
	- [x] ssh 연결
	- [x] Git 설치
		- [x] Github 키 발급 및 연결
	- [x] zsh 설치
		- [x] Oh My Zsh 설치
	- [x] Java 17 설치
	- [x] Elastic IP 주소 발급 
	- [x] Swap file을 이용해 메모리 부족 현상 해소 (Jar 빌드시 30분 걸리길래.. ㅎ => 1분으로 줄임)
	- [x] Docker 설치
	- [x] Docker-compose 설치
	- [x] 인바운딩 규칙 추가 22, 3306, 8080, 80 포트 오픈 
		- [x] SSH는 어떻게 관리?
	- [x] AWS IAM (회원 관리 및 권한 부여 할 수 있는 기능)
