### ISSUE TITLE
Category 기능

### ISSUE THREAD

**Issue by NaMooJoon** [ChatCode9/ChatCode-backend#24]
### 📄 Describe

Article(Ref. #16) 관련 category 도메인 생성 및 연결 작업

### ✅ Tasks

기능
- [x] Category 도메인 생성 및 테이블 연결
- [x] Article 작성하는 페이지에서 option list 조회 가능
- [x] Nav 바에서 option list 조회 가능
- [ ] Article CREATE시, category 연결 (many to one)

추가적인 고려사항
- [x] **Only admin** can access the create, update, delete functions.
