### ISSUE TITLE
AWS SDK for Java 2.x버전으로 업그레이드

### ISSUE THREAD

**Issue by minje0204** [ChatCode9/ChatCode-backend#29]
### 🤔 Describe

AWS SDK for Java 2.x버전으로 업그레이드

### ✅ Tasks

- [ ] IAM Identity Center으로 계정 재설정 
- [ ] AWS SDK for Java 2.x버전으로 업그레이드
- [ ] S3 파일 업로드 코드 2.x 버전에 맞게 업데이트
