### ISSUE TITLE
Authorization 테스트 관련 리팩토링

### ISSUE THREAD

**Issue by NaMooJoon** [ChatCode9/ChatCode-backend#47]
### 🔨 Describe

기존: OAuth2User 상속 받은 객체로 유저 관리
변경: OAuth2User와 UserDetails 동시 상속으로 유저 관리

이유: 로그인이 필요한 entry point에 대해서 통합 테스트 및 프론트 테스트를 진행할 때, 기존 [UserDetails](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/core/userdetails/UserDetails.html) 클래스를 사용하면 테스팅을 편하게 진행할 수 있음.

### ✅ Tasks

- [x] JUnit 테스팅 용이를 위한 User 및 LoginUser 구조 수정
- [x] 프론트 개발 Jwt 토큰 개발 테스트 => Http header에 담아도 권한 인증 처리 할 수 있도록
- [x] 테스트 유저 생성
