### ISSUE TITLE
JOOQ 환경 설정 및 샘플코드 작성

### ISSUE THREAD

**Issue by minje0204** [ChatCode9/ChatCode-backend#5]
### 🤔 Describe

DB에서 데이터를 가져올 방식 중 하나로 JOOQ를 세팅해보았습니다. JOOQ에서는 DB상 존재하는 스키마를 reverseengineering해서 스키마의 칼럼들을 모두 가지는 POJOS를 자동으로 생성해주는 code generate 기능이 있습니다.
추가적인 학습없이 간단하게 Raw SQL문을 작성할 수 있을 정도로 SQL과 차이가 없는 쿼리 문법을 가지고 있습니다.

### ✅ Tasks

- [x] Jooq 환경설정 해보기
- [x] Jooq 사용법을 알 수 있는 간단한 샘플 코드 작성해보기
- [ ] Why Jooq!? (Jooq말고 더 나은 옵션은 없는지)

### 🙋🏻 More

템플릿 세팅해주셔서 정말 감사해요 준현님 ~! 
넘나 이쁘고 편한것
