### ISSUE TITLE
Avatar 정보 추가

### ISSUE THREAD

**Issue by NaMooJoon** [ChatCode9/ChatCode-backend#57]
### 📄 Describe

디자인이 수정되면서, avatar 클래스에 저장해야할 필드가 하나 더 있어서 추가해야합니다.
<img width="893" alt="image" src="https://github.com/ChatCode9/ChatCode-backend/assets/47983023/0a008831-afc5-473b-a00a-e9f4f3dede57">

>"content": 개인프로필 페이지에 짧은 자기소개 글

>기존 avatar DB
> - id;
> - version;
> - activityPoint;
> - nickname;
> - picture;

### ✅ Tasks

- [x] DB 필드 추가
- [x] Entity class에 필드 추가
- [x] Ctrl, Service, Repository 수정
- [x] Dto 업데이트

**Comment by NaMooJoon** [comment]
@haemalgeumi 해당 issue 작업 완료하면 말씀드리겠습니닷
