### ISSUE TITLE
Article 작성시 category도 같이 포함해서 request

### ISSUE THREAD

**Issue by NaMooJoon** [ChatCode9/ChatCode-backend#68]
### 📄 Describe

<img width="1552" alt="image" src="https://github.com/ChatCode9/ChatCode-backend/assets/47983023/d554ed31-bc5f-4b69-8e67-7b5e3910bdf7">
위 사진은 현재 저희 figma 디자인이구요.

<img width="1552" alt="Screenshot 2024-07-11 at 4 01 14 PM" src="https://github.com/ChatCode9/ChatCode-backend/assets/47983023/c1b69395-d7f4-4765-a246-028d7ed95f1e">
위 사진은 현재 api 명세서에 개발된 [POST] /articles 엔트리포인트 입니다.

현재 request에 category를 등록하는 기능이 누락되어있더라구요.
해당 기능 개발해서 알리도록 하겠습니다.

### ✅ Tasks

- [x] DummyData: category {free, question} 추가
- [x] DTO: request body => category 추가
- [x] Entity: 현재 category ID가 UUID(String)로 지정 되어 있어 Long으로 DB 설계 수정.
- [x] ctrl, service, repository
  - [x] createArticle시, category 조회 및 foreign Key 연결
